- name: PING
  hosts: local
  connection: local
  tasks:
    - name: ping the server
      ansible.builtin.ping:


- name: PING1
  hosts: web 
  tasks:
    - name: Ping the server
      ansible.builtin.ping: 

