- name: print variables
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: "Ramu Gorla" 
  tasks:
    - name: print course information with variable values
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and Trainer is {{ TRAINER }}"