- name: Print both PLAYS and TASKS variables 
  hosts: web 
  vars: 
    COURSE: "ansible"
    DURATION: 10HRS
    TRAINER: "Ramu"
  tasks:
    - name: TASKS variables
      vars:
        COURSE: "Devops with AWS"
        DURATION: 120HRS
        TRAINER: "Siva"
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and Trainer is {{ TRAINER }}"
  
  
    - name: PLAYS variables
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and Trainer is {{ TRAINER }}"