- name: varaibles through prompt 
  hosts: local
  connection: local
  vars_prompt:
    - name: COURSE
      prompt: Please eneter course name
      private: false
    - name: DURATION
      prompt: please enetr time
      private: false
    - name: TRAINER
      prompt: please enter name
      private: false
  tasks:
    - name: give output 
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and Trainer is {{ TRAINER }}"