- name: varaibles preference 
  hosts: local
  connection: local
  vars: 
    GREET: "PLAYS"
  vars_files:
    - course.yaml
  vars_prompt:
    - name: GREET
      prompt: Please eneter wishes
      private: false
  tasks:
    - name: finding varaible preference
      # vars:
      #   GREET: "TASKS"
      ansible.builtin.debug:
        msg: "Hello from {{ GREET }}"


#1. Arguments
#2. TASKS