- name: Convert Prompt String to Integer
  hosts: local
  connection: local
  
  vars_prompt:
    - name: user_input
      prompt: "Enter a number"
      private: false

  tasks:
    - name: Convert string to integer and save as a fact
      ansible.builtin.set_fact:
        my_integer: "{{ user_input | int }}"

  
    - name: print if number is greater than 10 
      ansible.builtin.debug:
        msg: "Given number {{ my_number }} is greater than 10"
      when: user_input > 10 
   

