- name: Convert Prompt String to Integer
  hosts: local
  connection: local
  
  vars_prompt:
    - name: user_input
      prompt: "Enter a number"
      private: false

  tasks:
    - name: Convert string to integer and save as a fact
      ansible.builtin.set_fact:
        my_integer: "{{ user_input | int }}"

    - name: Display the variable type and value
      ansible.builtin.debug:
        msg: 
          - "Raw value from prompt: {{ user_input }}"
          - "Converted integer value: {{ my_integer }}"